site_name: Scrawler Components
repo_url: https://github.com/scrawler-labs/
repo_name: Github

nav:
    - Home: 'index.md'
    - Arca Orm: 
        - Getting Started: 'arca-orm/index.md'
        - Database & Drivers: 'arca-orm/database.md'
        - Models & Collections: 'arca-orm/models.md'
        - CRUD: 'arca-orm/crud.md'
        - Finding (Query): 'arca-orm/finding.md'
        - Relations: 'arca-orm/relations.md'
        - Collections: 'arca-orm/collections.md'
        - Using with Swoole & AmpPHP: 'arca-orm/swoole.md'
        - Changelog: 'arca-orm/changelog.md'

    - Router:
        - Getting started: 'router/index.md'
        - Automated Routing: 'router/how.md'
        - Website Homepage: 'router/home.md'
        - Redirection: 'router/redirect.md'
        - Server Configuration: 'router/server.md'

        
extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js

theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github

  
  palette:
    # Palette toggle for dark mode
    scheme: scrawler


  features:
    - navigation.section
    - navigation.expand
    - navigation.top
    - navigation.path
    - navigation.tabs
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link


markdown_extensions:
  - admonition
  - pymdownx.details

extra:
  generator: false

